server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: service-registry
  cloud:
    client:
      hostname: ${EUREKA_HOSTNAME:localhost}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}