spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/neuroforge
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/neuroforge_ai
spring.data.mongodb.database=neuroforge_ai
gemini.api.key='YOUR_API_KEY_HERE'
gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta/models